### ISSUE TITLE
Don't Understand This Issue

### ISSUE THREAD

**Issue by Jetlogan** [robotpy/pynetworktables2js#19]
`Traceback (most recent call last):
  File "pyinstaller\shim.py", line 6, in <module>
  File "pynetworktables2js\__main__.py", line 81, in main
  File "pynetworktables2js\__main__.py", line 37, in init_networktables
AttributeError: Values instance has no attribute 'dashboard'
Failed to execute script shim`

Anyone know what this means?

**Comment by virtuald** [comment]
It means I forgot to upload a fixed version after #18 was fixed. Try downloading 2017.0.2, sorry about that. :)

**Comment by Jetlogan** [comment]
Oh no problem. Thanks a lot!
