### ISSUE TITLE
Fix pyntcore compatibility issues

### ISSUE THREAD

**Issue by virtuald** [robotpy/pynetworktables2js#40]
Works great with pynetworktables, but there's a few missing pieces:

* NetworkTableInstance.getRemoteAddress missing
* NetworkTableInstance.addEntryListener/removeEntryListener behaviors have changed

**Comment by etiennebeaulac** [comment]
Hi @virtuald,

My team and I have encountered an error while running `pynetworktables2js/example/tornado_server.py`.

Stacktrace :
```
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/networktables/ws', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\Etienne\miniconda3\envs\firstA2021\lib\site-packages\tornado\websocket.py", line 954, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
  File "C:\Users\Etienne\miniconda3\envs\firstA2021\lib\site-packages\pynetworktables2js\tornado_handlers.py", line 27, in open
    self.ntserial = NTSerial(self.send_msg_threadsafe)
  File "C:\Users\Etienne\miniconda3\envs\firstA2021\lib\site-packages\pynetworktables2js\nt_serial.py", line 19, in __init__
    self.open()
  File "C:\Users\Etienne\miniconda3\envs\firstA2021\lib\site-packages\pynetworktables2js\nt_serial.py", line 51, in open
    NetworkTables.addGlobalListener(self._nt_on_change, immediateNotify=True)
AttributeError: '_pyntcore._ntcore.NetworkTablesInstance' object has no attribute 'addGlobalListener'
```

The same error happens in the few tests we have performed on different computers and different virtual environments (with the latest versions of `robotpy` and `pynetworktables2js`).

In the meantime, using the Windows executable works great.

Is this related to this issue? If not, I can open another issue ticket. Thanks for your help!

**Comment by virtuald** [comment]
It is related to this issue, yes.

**Comment by virtuald** [comment]
This is OBE now that pyntcore is separate.
